### ISSUE TITLE
Generator not available in NPM registry

### ISSUE THREAD

**Issue by mgruel** [cgross/generator-cg-angular15#1]
Hi Chris,

during installation of this generator, npm reports an error that the package is not available in the registry.

``` shell
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/generator-cg-angular15
npm ERR! 404 
npm ERR! 404  'generator-cg-angular15' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Best regards,
Meykel

PS:
I will install it via git url

**Comment by cgross** [comment]
Sorry I jumped the gun a bit when releasing the repo. I'm actually in the processes of converting this generator to use typescript instead of ES6. Should only be a few days. Then I'll publish it to npm.  Thanks.

**Comment by macnaranos** [comment]
Ok, thank you for clarification.
