### ISSUE TITLE
Missing output of "npm build"

### ISSUE THREAD

**Issue by martin-s** [cgross/generator-cg-angular15#2]
I'm actually not really up-to-date with all new updates you added, but I really appreciate the removal of other dependencies, like bower, grunt.
When running command "npm build" on a fresh new project (no changes made), I would expect a dist-folder with a _bundle.js_ in it. The command itself runs fine, just returns an "ok" at the end. Can you help out?
A command "npm start" runs the webdev-server.

**Comment by cgross** [comment]
Try "npm run build". Build is a general npm command and you need "npm run build" to invoke the script alias.

**Comment by martin-s** [comment]
Thanks, good hint. Missed the keyword.
Issue can be closed.
